set_nomes_masculinos_default = {
    'A-ki-til', 'AaravI', 'Aaron', 'Aarón', 'Aayan', 'Ab', 'Abbie', 'Abd', 'Abdallah', 'Abdel',
    'Abdelkader', 'Abdellah', 'Abderrahman', 'Abderrahmane', 'Abdiel', 'Abdoul', 'Abdoulaye',
    'Abdoullah', 'Abdullah', 'Abdón', 'Abe', 'Abe', 'Abel', 'Abie', 'Abihail', 'Abilio',
    'Abimael', 'Abner', 'Aboubacar', 'Aboubakar', 'Abraham', 'Abram', 'Abundio', 'Acab', 'Acacio',
    'Ace', 'Achille', 'Achraf', 'Ad', 'Adal', 'Adalbert', 'Adalberto', 'Adam', 'Adama', 'Adame',
    'Adan', 'Addie', 'Addy', 'Ade', 'Adel', 'Adelbert', 'Adem', 'Aden', 'Adil', 'Adir', 'Adiran',
    'Adler', 'Adolfo', 'Adonis', 'Adrian', 'Adriano', 'Adriel', 'Adrien', 'Adrián', 'Adán',
    'Aedan', 'Afrodisio', 'Agapi', 'Agapito', 'Agni', 'Agustin', 'Agustín', 'Ahmad', 'Ahmed',
    'Ahmed', 'Ahmet', 'Ahmir', 'Ahzià', 'Aidan', 'Aiden', 'Aiko', 'Aimé', 'Aitor', 'Aketx',
    'Akram', 'Aksel', 'Aksil', 'Alain', 'Alan', 'Alano', 'Alaric', 'Alassane', 'Alastair',
    'Alaster', 'Alatz', 'Alban', 'Albano', 'Albert', 'Alberto', 'Albin', 'Albino', 'Alcibíades',
    'Aldahir', 'Aldan', 'Alden', 'Aldo', 'Aldán', 'Alec', 'Aleck', 'Aleix', 'Alejandro',
    'Alessandro', 'Alessio', 'Alex', 'Alexander', 'Alexandre', 'Alexandre', 'Alexandru', 'Alexis',
    'Alexy', 'Alf', 'Alfie', 'Alfonso', 'Alfred', 'Alfredo', 'Alger', 'Algernon', 'Algie', 'Algy',
    'Ali', 'Ali', 'Alijah', 'Alistair', 'Alister', 'Alix', 'Allan', 'Allan', 'Allen', 'Allister',
    'Alonso', 'Alonzo', 'Aloys', 'Aloïs', 'Alpha', 'Alphonse', 'Alphonso', 'Alton', 'Alucio',
    'Alva', 'Alvah', 'Alvan', 'Alvaro', 'Alvin', 'Alwin', 'Alwyn', 'Aly', 'Amadeo', 'Amado',
    'Amador', 'Amadou', 'Amadís', 'Amalio', 'Amancio', 'Amar', 'Amari', 'Amaro', 'Amaru',
    'Amasvindo', 'Amaury', 'Amaël', 'Ambie', 'Ambiórix', 'Ambroise', 'Ambrose', 'Ambrosio',
    'Ameer', 'Amelio', 'Amias', 'Amin', 'Amine', 'Amir', 'Amir', 'Amiri', 'Amjad', 'Amonario',
    'Amori', 'Amos', 'Anakin', 'Anas', 'Anass', 'Anastasio', 'Anatole', 'Anaël', 'Andeka', 'Ander',
    'Anders', 'Anderson', 'Andoni', 'Andre', 'Andrea', 'Andreas', 'Andrei', 'Andres', 'Andrew',
    'Andros', 'André', 'Andréa', 'Andréas', 'Andrés', 'Andy', 'Andy', 'Anes', 'Ange', 'Angel',
    'Angelo', 'Angus', 'Aniceto', 'Anis', 'Anouar', 'Anse', 'Ansel', 'Anselm', 'Anselme',
    'Anselmo', 'Antelmo', 'Antenor', 'Anthony', 'Anthony Gabriel', 'Antoine', 'Antoine', 'Anton',
    'Antone', 'Antonin', 'Antonio', 'Antony', 'Antxon', 'Antíoco', 'Antón', 'Antônio', 'Anwyl',
    'Anxo', 'Aomar', 'Apollo', 'Apolo', 'Apolonio', 'Aquiles', 'Aquilino', 'Aram', 'Aratz', 'Arch',
    'Archer', 'Archibald', 'Archie', 'Archie', 'Ardaitz', 'Ares', 'Argi', 'Argider', 'Argimiro',
    'Ari', 'Arian', 'Ariel', 'Aries', 'Aris', 'Aristide', 'Aritz', 'Arjun', 'Arlen', 'Arlo',
    'Armand', 'Armando', 'Armani', 'Armel', 'Armengol', 'Arnau', 'Arnaud', 'Arnaud', 'Arnaut',
    'Arnie', 'Arnold', 'Arnulfo', 'Aron', 'Aronn', 'Arsenio', 'Arsène', 'Art', 'Art', 'Artai',
    'Arthur', 'Arthur Miguel', 'Arthus', 'Artie', 'Artur', 'Arturo', 'Artús', 'Aryan', 'Asa',
    'Asafe', 'Asaiah', 'Asel', 'Ash', 'Asher', 'Ashton', 'Ashur', 'Asier', 'Assil', 'Asteri',
    'Astor', 'Atanasio', 'Atharv', 'Atilano', 'Atlas', 'Atreus', 'Atticus', 'Aubin', 'Aubrey',
    'Augie', 'August', 'Auguste', 'Augustin', 'Augustine', 'Augusto', 'Augustus', 'Aurel',
    'Aurelio', 'Auritz', 'Aurèle', 'Aurélien', 'Austin', 'Austin', 'Auxence', 'Avelino', 'Avery',
    'Avi', 'Avon', 'Avy', 'Avyaan', 'Axel', 'Axl', 'Axton', 'Ayan', 'Ayaz', 'Aydan', 'Ayden',
    'Aylan', 'Ayman', 'Aymane', 'Aymen', 'Aymeric', 'Ayoub', 'Azad', 'Azael', 'Azai', 'Azariah',
    'Azarías', 'Aziel', 'Aziz', 'Azrael', 'Azriel', 'Azubuike', 'Aïdan', 'Aïden', 'Aïssa', 'Badis',
    'Badr', 'Bakary', 'Baker', 'Baladeva', 'Baladi', 'Baldie', 'Baldwin', 'Baltasar', 'Balthazar',
    'Baltz', 'Banks', 'Baptiste', 'Bardo', 'Barnard', 'Barney', 'Barnie', 'Barrett', 'Barrie',
    'Barry', 'Bart', 'Bartholomew', 'Bartlett', 'Bartley', 'Bartolo', 'Bartolomé', 'Barty',
    'Basie', 'Basil', 'Basile', 'Basilio', 'Bass', 'Bastian', 'Bastien', 'Bat', 'Batiste',
    'Batty', 'Baudilio', 'Bautista', 'Baylor', 'Bayron', 'Baz', 'Bazkoare', 'Bear', 'Beau',
    'Beckett', 'Beckham', 'Belenos', 'Belenus', 'Bellamy', 'Beloveso', 'Beltrán', 'Ben',
    'Benedict', 'Benedicto', 'Benicio', 'Benigno', 'Benito', 'Benjamin', 'Benjamín', 'Benjie',
    'Benjy', 'Bennet', 'Bennett', 'Bennie', 'Benny', 'Benoît', 'Benoit', 'Benson', 'Bentley',
    'Bento', 'Benício', 'Berat', 'Beraun', 'Bernard', 'Bernardo', 'Bernat', 'Berney', 'Bernie',
    'Bert', 'Bert', 'Berthold', 'Bertie', 'Bertie', 'Bertram', 'Bertrand', 'Beto', 'Bieito',
    'Biel', 'Bikendi', 'Biktor', 'Bilal', 'Bilal', 'Bilel', 'Bill', 'Bill', 'Billie', 'Billie',
    'Billy', 'Bittor', 'Bjorn', 'Blair', 'Blake', 'Blas', 'Blaze', 'Bo', 'Bob', 'Bob', 'Bobbie',
    'Bobby', 'Bobby', 'Bode', 'Boden', 'Bodhi', 'Bodie', 'Bonifacio', 'Boone', 'Booz', 'Boris',
    'Boston', 'Boubacar', 'Bowen', 'Brad', 'Brad', 'Braden', 'Bradford', 'Bradley', 'Brady',
    'Brahim', 'Brais', 'Bram', 'Bran', 'Brand', 'Branden', 'Brandon', 'Brandy', 'Brantley',
    'Braxton', 'Brayan', 'Brayden', 'Braylen', 'Braylon', 'Brecken', 'Breixo', 'Brenan',
    'Brendan', 'Brennan', 'Breno', 'Brent', 'Brenton', 'Breogán', 'Bret', 'Brett', 'Briac',
    'Brian', 'Briar', 'Briccio', 'Bricio', 'Bridger', 'Brieuc', 'Briggs', 'Brixton', 'Brock',
    'Broderick', 'Brodie', 'Brody', 'Bronson', 'Brooks', 'Brose', 'Bruce', 'Bruno', 'Bryan',
    'Bryant', 'Bryce', 'Brycen', 'Bryson', 'Bud', 'Buenaventura', 'Burt', 'Burton', 'Byron',
    'Cade', 'Caden', 'Caiden', 'Cain', 'Caio', 'Cairo', 'Cal', 'Cal', 'Caleb', 'Calixte',
    'Calixto', 'Callahan', 'Callan', 'Callen', 'Callum', 'Calum', 'Calvin', 'Cam', 'Camden',
    'Cameron', 'Camil', 'Camille', 'Camilo', 'Can', 'Canaan', 'Cannon', 'Carataco', 'Carel',
    'Carey', 'Carl', 'Carl', 'Carlo', 'Carlos', 'Carmelo', 'Carrol', 'Carroll', 'Carry', 'Carson',
    'Carter', 'Cartier', 'Carwyn', 'Cary', 'Cas', 'Case', 'Casen', 'Casey', 'Cash', 'Casimiro',
    'Cason', 'Caspar', 'Casper', 'Caspian', 'Cass', 'Cassian', 'Cassius', 'Castiel', 'Cauã',
    'Cayden', 'Cayson', 'Caín', 'Cearbhall', 'Cecil', 'Ced', 'Cedric', 'Cedrick', 'Celedonio',
    'Cernunnos', 'Cesar', 'Chad', 'Chahine', 'Chaim', 'Chance', 'Chandler', 'Charles', 'Charles',
    'Charley', 'Charli', 'Charlie', 'Charly', 'Chas', 'Chase', 'Cheikh', 'Chelem', 'Chema',
    'Chente', 'Chester', 'Chet', 'Chinweike', 'Chosen', 'Chris', 'Christian', 'Christophe',
    'Christopher', 'Christy', 'Chuck', 'Cian', 'Cibrán', 'Cillian', 'Cipriano', 'Cirilo', 'Ciro',
    'Cis', 'Clair', 'Clare', 'Clarence', 'Clark', 'Clarke', 'Claud', 'Claude', 'Claude', 'Clay',
    'Clay', 'Clayton', 'Clem', 'Clement', 'Clemente', 'Cliff', 'Clifford', 'Clint', 'Clinton',
    'Clive', 'Clovis', 'Clyde', 'Clément', 'Cody', 'Cohen', 'Colby', 'Cole', 'Coleson', 'Colin',
    'Collin', 'Colson', 'Colt', 'Colten', 'Colter', 'Colton', 'Con', 'Concho', 'Conner',
    'Connolley', 'Connor', 'Conny', 'Conor', 'Conrad', 'Conrado', 'Constant', 'Constantin',
    'Cooper', 'Corban', 'Corbin', 'Corentin', 'Corey', 'Cornelius', 'Corney', 'Corny', 'Cory',
    'Cosme', 'Craig', 'Creed', 'Crew', 'Cris', 'Crispín', 'Cristian', 'Cristiano', 'Crisóstomo',
    'Crue', 'Cruz', 'Críspulo', 'Cuchulain', 'Cullen', 'Curt', 'Curtis', 'Cy', 'Cyprien', 'Cyril',
    'Cyrus', 'Cédric', 'Célestin', 'Célian', 'César', 'Côme', 'Dabi', 'Dagda', 'Dago',
    'Dagoberto', 'Dailin', 'Dakari', 'Dakota', 'Dale', 'Dale', 'Dalil', 'Dallas', 'Dalton',
    'Daly', 'Damari', 'Damen', 'Damian', 'Damien', 'Damir', 'Damián', 'Damon', 'Dan', 'Dane',
    'Dangelo', 'Daniel', 'Danny', 'Dante', 'Dany', 'Daoud', 'Daouda', 'Darek', 'Daren', 'Dari',
    'Darian', 'Dariel', 'Dario', 'Darius', 'Darrel', 'Darrell', 'Darren', 'Darry', 'Darryl',
    'Darwin', 'Daryl', 'Darío', 'Dash', 'Dave', 'Davet', 'Davey', 'Davi', 'Davi Lucas',
    'Davi Lucca', 'Davi Luiz', 'Davi Miguel', 'Davian', 'David', 'Davie', 'Davis', 'Davy',
    'Dawit', 'Dawson', 'Dax', 'Daxton', 'Dayan', 'Deacon', 'Dean', 'Dean', 'Deane', 'Declan',
    'Defín', 'Del', 'Delbert', 'Dell', 'Demba', 'Demetrius', 'Demian', 'Demócrito', 'Den',
    'Denis', 'Denis', 'Dennis', 'Denny', 'Denver', 'Denís', 'Derek', 'Derrick', 'Derry', 'Des',
    'Desmond', 'Devin', 'Devon', 'Dex', 'Dexter', 'Dick', 'Diego', 'Dilan', 'Dilber', 'Dillon',
    'Dimitri', 'Diogo', 'Dion', 'Dionisio', 'Dior', 'Diviciaco', 'Diégo', 'Djibril', 'Djulian',
    'Dob', 'Dogartzi', 'Dolf', 'Dolph', 'Dom', 'Domenic', 'Domenick', 'Domingo', 'Dominic',
    'Dominick', 'Don', 'Donald', 'Donaldo', 'Donardo', 'Donato', 'Donnie', 'Donny', 'Donovan',
    'Dorian', 'Doug', 'Doug', 'Douglas', 'Douglass', 'Doyle', 'Drake', 'Drako', 'Drew', 'Drew',
    'Drew', 'Driss', 'Druso', 'Duane', 'Dud', 'Duddy', 'Dudley', 'Dugan', 'Duke', 'Duncan',
    'Dunixi', 'Dunk', 'Dunny', 'Dustin', 'Dusty', 'Dutton', 'Dwayne', 'Dwight', 'Dylan', 'Dáire',
    'Dámaso', 'Eamon', 'Earl', 'Earle', 'Earnest', 'Easton', 'Ebrahim', 'Ed', 'Ed', 'Eddie',
    'Eddy', 'Edem', 'Eden', 'Edey', 'Edgar', 'Edison', 'Edmond', 'Edmund', 'Edorta', 'Edouard',
    'Eduardo', 'Edward', 'Edwin', 'Efraín', 'Egan', 'Egbert', 'Ehud', 'Einar', 'Eirian', 'Eithan',
    'Ekaitz', 'Eki', 'El', 'Eladi', 'Elbert', 'Elbio', 'Eldred', 'Eleuterio', 'Eli', 'Eliakim',
    'Eliam', 'Elian', 'Elias', 'Eliaz', 'Elie', 'Eliel', 'Elijah', 'Elio', 'Eliodoro', 'Eliot',
    'Eliott', 'Eliseo', 'Elisha', 'Elixi', 'Elián', 'Elliot', 'Elliott', 'Ellis', 'Elmer',
    'Eloan', 'Eloi', 'Elouan', 'Elouann', 'Eloy', 'Elton', 'Elvin', 'Elvis', 'Elwin', 'Elwood',
    'Elwyn', 'Ely', 'Elyan', 'Elyas', 'Elyes', 'Elyo', 'Elí', 'Elías', 'Em', 'Emanuel', 'Emerico',
    'Emerson', 'Emery', 'Emeterio', 'Emil', 'Emile', 'Emiliano', 'Emilien', 'Emilio', 'Emir',
    'Emiri', 'Emmanuel', 'Emmery', 'Emmet', 'Emmett', 'Emmitt', 'Emory', 'Emre', 'Emrys', 'Enaël',
    'Endor', 'Endrike', 'Eneas', 'Eneko', 'Enes', 'Enetz', 'Ennio', 'Enoch', 'Enoha', 'Enrico',
    'Enrique', 'Enzo', 'Enzo Gabriel', 'Epifanio', 'Erasmo', 'Erasmus', 'Eren', 'Eric', 'Erick',
    'Erik', 'Eritz', 'Ermias', 'Ernest', 'Ernesto', 'Ernie', 'Eros', 'Errol', 'Erv', 'Ervin',
    'Erwan', 'Erwann', 'Erwin', 'Esaú', 'Estanislao', 'Esteban', 'Estevão', 'Estéban', 'Esus',
    'Etan', 'Ethan', 'Ethann', 'Etienne', 'Etor', 'Eufrasio', 'Eugene', 'Eugenio', 'Eugène',
    'Euken', 'Eulogio', 'Eustace', 'Ev', 'Evan', 'Evan', 'Evander', 'Evann', 'Evaristo',
    'Everaldo', 'Everard', 'Everest', 'Everett', 'Ewan', 'Ewen', 'Ewenn', 'Eyden', 'Eymen',
    'Eythan', 'Ezekiel', 'Ezequiel', 'Ezio', 'Ezra', 'Ezrah', 'Eñaut', 'Fab', 'Fabe', 'Fabian',
    'Fabien', 'Fabien', 'Fabio', 'Fabián', 'Fabrizio', 'Faisal', 'Fares', 'Farid', 'Farès',
    'Faustino', 'Fausto', 'Feliciano', 'Felipe', 'Felix', 'Ferdie', 'Ferdinand', 'Fergal',
    'Fergie', 'Fergus', 'Ferguson', 'Fermín', 'Fernando', 'Ferran', 'Fidel', 'Filip', 'Finley',
    'Finn', 'Finn', 'Finnegan', 'Finnley', 'Fionn', 'Firas', 'Fisher', 'Fitzwilliam', 'Flavien',
    'Flavio', 'Fletcher', 'Flocelo', 'Florencio', 'Florent', 'Florentino', 'Florian', 'Floy',
    'Floy', 'Floyd', 'Flynn', 'Ford', 'Ford', 'Forest', 'Forrest', 'Fran', 'Francis', 'Francisco',
    'Franco', 'Frank', 'Frankie', 'Franklin', 'Franklyn', 'Franky', 'Frantzes', 'Frantzisko',
    'François', 'François', 'Fred', 'Freddie', 'Freddie', 'Freddy', 'Frederic', 'Frederick',
    'Fredric', 'Fredrick', 'Froilán', 'Fructuoso', 'Frutos', 'Fynn', 'Félix', 'Gaara', 'Gabby',
    'Gabe', 'Gabe', 'Gabin', 'Gabriel', 'Gabryel', 'Gaby', 'Gadiel', 'Gael', 'Gaela', 'Gage',
    'Galip', 'Gallagher', 'Galván', 'Ganiz', 'Gannicus', 'Gari', 'Garnik', 'Garret', 'Garrett',
    'Garry', 'Gary', 'Gaspar', 'Gaspard', 'Gaston', 'Gatien', 'Gatlin', 'Gauthier', 'Gautier',
    'Gavin', 'Gaétan', 'Gaël', 'Gaëtan', 'Genaro', 'Gene', 'Geoffrey', 'Geordie', 'George',
    'Georges', 'Georgie', 'Gerald', 'Gerard', 'Gerardo', 'Germain', 'Germán', 'Gerry', 'Gerwyn',
    'Gian', 'Gianni', 'Gideon', 'Gil', 'Gilbert', 'Gino', 'Ginés', 'Giovanni', 'Giulian',
    'Giuliano', 'Giulio', 'Giuseppe', 'Glen', 'Glen', 'Glenn', 'Gonzalo', 'Goran', 'Gordon',
    'Gordy', 'Goyo', 'Grady', 'Graham', 'Grant', 'Grayson', 'Greg', 'Gregg', 'Gregor', 'Gregorio',
    'Gregory', 'Grey', 'Greyson', 'Griff', 'Griffin', 'Griffith', 'Grégoire', 'Grégory', 'Guido',
    'Guiem', 'Guilhem', 'Guilherme', 'Guillaume', 'Guillaume', 'Guillermo', 'Guiu', 'Gumersindo',
    'Gunnar', 'Gunner', 'Gunther', 'Gus', 'Gussy', 'Gust', 'Gustave', 'Gustavo', 'Gustus', 'Guy',
    'Gwyddyon', 'Gérard', 'Günter', 'Habib', 'Hadrian', 'Hadrien', 'Hakim', 'Hal', 'Hal', 'Hamza',
    'Hamza', 'Hank', 'Hans', 'Hansel', 'Hariman', 'Harlan', 'Harlem', 'Harley', 'Harold', 'Haron',
    'Harone', 'Haroun', 'Harris', 'Harrison', 'Harry', 'Harsal', 'Harve', 'Harvey', 'Hasani',
    'Hassan', 'Hassan', 'Hayden', 'Hayes', 'Heath', 'Heathcliff', 'Hector', 'Hedi', 'Heitor',
    'Hendrix', 'Henri', 'Henri', 'Henrik', 'Henrique', 'Henry', 'Herb', 'Herbert', 'Herman',
    'Hermenegildo', 'Hermes', 'Herminio', 'Hernan', 'Herodes', 'Hervé', 'Hezekiah', 'Higinio',
    'Hilario', 'Hilary', 'Hill', 'Hillary', 'Hillie', 'Hilly', 'Hippolyte', 'Hipócrates',
    'Hipólito', 'Holden', 'Homer', 'Homero', 'Horace', 'Horatio', 'Houston', 'Howard', 'Howie',
    'Hube', 'Hubert', 'Huck', 'Hudson', 'Hugh', 'Hughie', 'Hugo', 'Humberto', 'Humph', 'Humphrey',
    'Humphry', 'Hunter', 'Huxley', 'Héctor', 'Hélio', 'Hélios', 'Hércules', 'Iago', 'Ian', 'Ibai',
    'Iban', 'Ibon', 'Ibrahim', 'Ibrahim', 'Ibrahima', 'Idris', 'Idriss', 'Idrissa', 'Iggy',
    'Ignacio', 'Ignatius', 'Igor', 'Igotz', 'Ihsan', 'Ike', 'Iker', 'Ilan', 'Ilann', 'Ilhan',
    'Ilian', 'Ilias', 'Illan', 'Ilyan', 'Ilyane', 'Ilyas', 'Ilyass', 'Ilyes', 'Ilyess', 'Ilyès',
    'Ilán', 'Imad', 'Immanuel', 'Imran', 'Imrane', 'Indalecio', 'Inocencio', 'Ion', 'Ira',
    'Ireneo', 'Irvin', 'Irvine', 'Irving', 'Irwin', 'Irwin', 'Isaac', 'Isaak', 'Isacio',
    'Isador', 'Isadore', 'Isaiah', 'Isaias', 'Isaías', 'Isaïah', 'Ishaan', 'Ishak', 'Ishaq',
    'Isidor', 'Isidore', 'Isidoro', 'Islam', 'Islem', 'Ismael', 'Ismail', 'Ismaël', 'Ismaïl',
    'Israel', 'Issa', 'Issac', 'Issam', 'Ivaan', 'Ivan', 'Ivan', 'Ivar', 'Ivor', 'Iván', 'Iyad',
    'Iyed', 'Izaiah', 'Izan', 'Izzy', 'Jaaziel', 'Jace', 'Jacinto', 'Jack', 'Jackie', 'Jackson',
    'Jacky', 'Jacky', 'Jacob', 'Jacobo', 'Jacques', 'Jacques', 'Jad', 'Jaden', 'Jadiel', 'Jael',
    'Jagger', 'Jahyan', 'Jaiden', 'Jaime', 'Jaimin', 'Jairo', 'Jakai', 'Jakari', 'Jake', 'Jake',
    'Jakob', 'Jalen', 'Jalil', 'Jamari', 'James', 'Jameson', 'Jamie', 'Jamir', 'Jamison', 'Jan',
    'Jano', 'Jared', 'Jaret', 'Jarod', 'Jarvis', 'Jase', 'Jasiah', 'Jason', 'Jasper', 'Jassem',
    'Jassim', 'Jasón', 'Javier', 'Jawad', 'Jawed', 'Jax', 'Jaxon', 'Jaxson', 'Jaxton', 'Jaxx',
    'Jaxxon', 'Jay', 'Jay', 'Jayce', 'Jayceon', 'Jayden', 'Jaylen', 'Jayson', 'Jaz', 'Jaziel',
    'Jaír de Galaad', 'Jean', 'Jean', 'Jean-Baptiste', 'Jeb', 'Jeb', 'Jed', 'Jedidiah', 'Jeff',
    'Jefferson', 'Jeffery', 'Jeffrey', 'Jehoram', 'Jem', 'Jensen', 'Jeremiah', 'Jeremias',
    'Jeremy', 'Jeremías', 'Jericho', 'Jerome', 'Jerry', 'Jervis', 'Jess', 'Jesse', 'Jessie',
    'Jessim', 'Jessy', 'Jesús', 'Jett', 'Jibril', 'Jigme', 'Jim', 'Jimmie', 'Jimmy', 'Jiraiya',
    'Jiram', 'Jo', 'Joachim', 'Joakim', 'Joan', 'Joanix', 'Joao', 'Joaquim', 'Joaquin', 'Joaquín',
    'Jody', 'Joe', 'Joel', 'Joey', 'Johan', 'Johann', 'John', 'Johnathan', 'Johnny', 'Jolan',
    'Jon', 'Jonah', 'Jonas', 'Jonathan', 'Jones', 'Jonny', 'Jonás', 'Jordan', 'Jordán', 'Jorge',
    'Joris', 'Jos', 'Jose', 'Joseph', 'Josh', 'Joshua', 'Josiah', 'Joss', 'Josue', 'Josué',
    'José', 'José Miguel', 'José Pedro', 'Joud', 'Jovanni', 'Joziah', 'João', 'João Gabriel',
    'João Guilherme', 'João Lucas', 'João Miguel', 'João Pedro', 'João Vitor', 'Joël', 'Jrue',
    'Juan', 'Juancho', 'Jud', 'Judah', 'Jude', 'Judson', 'Jule', 'Julen', 'Jules', 'Julian',
    'Juliann', 'Julien', 'Julio', 'Julius', 'Julián', 'Julyan', 'Junayd', 'Junior', 'Jus',
    'Justin', 'Justo', 'Jérémie', 'Jérémy', 'Jürgen', 'Kaan', 'Kabir', 'Kade', 'Kaden', 'Kadet',
    'Kael', 'Kahil', 'Kai', 'Kai', 'Kaiden', 'Kairo', 'Kais', 'Kaisen', 'Kaiser', 'Kaison',
    'Kaizen', 'Kaleb', 'Kalel', 'Kalen', 'Kalvin', 'Kamal', 'Kamari', 'Kamden', 'Kamel',
    'Kameron', 'Kamil', 'Kamryn', 'Kanan', 'Kanda', 'Kane', 'Kannon', 'Kareem', 'Karim', 'Karl',
    'Karson', 'Karter', 'Kartier', 'Kase', 'Kasen', 'Kasey', 'Kash', 'Kashton', 'Kason', 'Kassim',
    'Kauê', 'Kayce', 'Kayden', 'Kaylan', 'Kayron', 'Kays', 'Kaysen', 'Kayson', 'Kaïs', 'Kaïss',
    'Keanu', 'Keaton', 'Keegan', 'Keith', 'Kel', 'Kellan', 'Kellen', 'Kelley', 'Kelly', 'Kelvin',
    'Kelyan', 'Ken', 'Kenai', 'Kenan', 'Kendall', 'Kendrick', 'Kenji', 'Kenneth', 'Kenny', 'Kent',
    'Kenzi', 'Kenzo', 'Kenzy', 'Kerizo', 'Kerman', 'Kerr', 'Kester', 'Kester', 'Kev', 'Kevin',
    'Keylan', 'Keziah', 'Khai', 'Khalid', 'Khalid', 'Khalil', 'Khalis', 'Khari', 'Khaza', 'Kiaan',
    'Kian', 'Kiefer', 'Kieran', 'Kilian', 'Killian', 'Kilyan', 'Kingsley', 'Kingston', 'Kinsley',
    'Kip', 'Kirk', 'Kiyan', 'Klaus', 'Knox', 'Koa', 'Kobe', 'Koda', 'Koen', 'Kohen', 'Kolson',
    'Kolton', 'Kon', 'Kooper', 'Korbin', 'Krew', 'Kris', 'Krishna', 'Kristian', 'Kristof',
    'Kristofer', 'Kristopher', 'Kuno', 'Kurt', 'Kurt', 'Kye', 'Kylan', 'Kyle', 'Kylen', 'Kyler',
    'Kylian', 'Kyliann', 'Kyllian', 'Kylo', 'Kyree', 'Kyrie', 'Kyro', 'Kyson', 'Kélio', 'Kélyan',
    'Kévin', 'Labán', 'Lachlan', 'Lambert', 'Lamine', 'Lamont', 'Lance', 'Lancelot', 'Landen',
    'Landon', 'Landyn', 'Lane', 'Langston', 'Larry', 'Lars', 'Lassana', 'Launcelot', 'Laureano',
    'Lauren', 'Laurence', 'Laurie', 'Lavi', 'Lawrence', 'Lawrie', 'Lawson', 'Layan', 'Layden',
    'Layne', 'Layton', 'Layvin', 'Lazare', 'Leandre', 'Leandro', 'Ledger', 'Lee', 'Leeroy',
    'Legacy', 'Legend', 'Leif', 'Leigh', 'Leighton', 'Leland', 'Lemuel', 'Len', 'Lennie',
    'Lennon', 'Lennox', 'Lenny', 'Leny', 'Lenzo', 'Leo', 'Leocadio', 'Leon', 'Leonard',
    'Leonardo', 'Leonel', 'Leonidas', 'Leopold', 'Leopoldo', 'Leovigildo', 'Leroy', 'Lesley',
    'Leslie', 'Lester', 'Lev', 'Levi', 'Leví', 'Lew', 'Lewie', 'Lewis', 'Lex', 'León', 'Liam',
    'Liam', 'Lian', 'Liesl', 'Lige', 'Liham', 'Lilian', 'Lilio', 'Lin', 'Linc', 'Lincoln',
    'Lindon', 'Lindsay', 'Lindsey', 'Lino', 'Linus', 'Lionel', 'Lisandro', 'Lisandru',
    'Lissandro', 'Livio', 'Lix', 'Liyam', 'Llew', 'Llewellyn', 'Lloyd', 'Loan', 'Loann',
    'Lochlan', 'Loevan', 'Logan', 'Lohan', 'Lohann', 'Lois', 'Lon', 'London', 'Lonnie', 'Lonny',
    'Lonny', 'Lony', 'Loot', 'Lope', 'Loqman', 'Loren', 'Lorence', 'Lorenzo', 'Loris', 'Lorys',
    'Lou', 'Lou', 'Louay', 'Louca', 'Loucas', 'Louie', 'Louis', 'Louison', 'Louka', 'Loukas',
    'Lounis', 'Lounès', 'Loup', 'Lovell', 'Lowell', 'Lowen', 'Loy', 'Loyal', 'Loyd', 'Loyde',
    'Loévan', 'Loïc', 'Loïs', 'Lu', 'Luan', 'Luben', 'Lubin', 'Luc', 'Luc', 'Luca', 'Lucas',
    'Lucca', 'Lucenzo', 'Lucian', 'Luciano', 'Lucien', 'Lucius', 'Ludovic', 'Lug', 'Luis',
    'Luiz Henrique', 'Luiz Miguel', 'Luka', 'Lukas', 'Luke', 'Luth', 'Luther', 'Lux', 'Lyall',
    'Lyam', 'Lyes', 'Lyham', 'Lyle', 'Lylian', 'Lylio', 'Lyn', 'Lyndon', 'Lynn', 'Lysandre',
    'Lyss', 'Lyvio', 'Léandre', 'Léandro', 'Lélio', 'Léni', 'Lény', 'Léo', 'Léo-Paul', 'Léon',
    'Léonard', 'Léonovo', 'Léopold', 'Lévi', 'Lucho', 'Mac', 'Macario', 'Mack', 'Mack', 'Macéo', 'Madden',
    'Maddox', 'Mady', 'Mael', 'Magnus', 'Mahamadou', 'Mahdi', 'Maher', 'Mahir', 'Mahmoud', 'Maho',
    'Mahé', 'Maiol', 'Major', 'Makai', 'Mal', 'Malachi', 'Malakai', 'Malc', 'Malcolm', 'Malek',
    'Malick', 'Malik', 'Malo', 'Malone', 'Malonn', 'Mamadou', 'Manannan', 'Mani', 'Mannie',
    'Mannie', 'Manny', 'Manoa', 'Manoah', 'Manoel', 'Manoé', 'Manuel', 'Mao', 'Marc', 'Marceau',
    'Marcel', 'Marcel', 'Marcellus', 'Marcelo', 'Marco', 'Marcos', 'Marcus', 'Marduk', 'Marin',
    'Mario', 'Marion', 'Marius', 'Mark', 'Mark', 'Marley', 'Marlon', 'Marshal', 'Marshall',
    'Mart', 'Martin', 'Martiño', 'Marty', 'Martí', 'Martín', 'Marv', 'Marvin', 'Marvyn', 'Marwan',
    'Marwane', 'Mason', 'Mat', 'Mateo', 'Matheo', 'Matheus', 'Mathew', 'Mathias', 'Mathieu',
    'Mathis', 'Mathys', 'Mathéis', 'Mathéo', 'Matias', 'Matis', 'Matisse', 'Matt', 'Matteo',
    'Matthew', 'Matthias', 'Matthieu', 'Matthéo', 'Mattia', 'Mattie', 'Mattis', 'Matty', 'Mattéo',
    'Matys', 'Matéo', 'Matías', 'Maurice', 'Mauricio', 'Maurino', 'Mauro', 'Maverick', 'Max',
    'Maxence', 'Maxim', 'Maxime', 'Maximilian', 'Maximiliano', 'Maximilien', 'Maximo', 'Maximus',
    'Maxton', 'Maxwell', 'Mayeul', 'Maylan', 'Maynard', 'Mayron', 'Mayronn', 'Mayson', 'Maé',
    'Maël', 'Maëlan', 'Mccoy', 'Meginhard', 'Mehdi', 'Mehmet', 'Meinardo', 'Meir', 'Mekhi', 'Mel',
    'Melchor', 'Melih', 'Melitón', 'Melvin', 'Melvyn', 'Menzo', 'Merill', 'Merle', 'Merlin',
    'Merlín', 'Merril', 'Merrill', 'Merv', 'Mervin', 'Messiah', 'Micah', 'Michael', 'Michel',
    'Michio', 'Mick', 'Mick', 'Mickael', 'Mickaël', 'Mickey', 'Micky', 'Miguel', 'Mikail',
    'Mikaïl', 'Mike', 'Mikey', 'Milan', 'Milann', 'Miles', 'Milhan', 'Milhane', 'Miller',
    'Milo', 'Milos', 'Milt', 'Milton', 'Milàn', 'Milán', 'Miran', 'Mirko', 'Misael', 'Mishka',
    'Mitch', 'Mitchell', 'Mo', 'Moe', 'Mohamed', 'Mohamed', 'Mohamed-Ali', 'Mohamed-Amine',
    'Mohammad', 'Mohammed', 'Moises', 'Moisés', 'Moncho', 'Monroe', 'Montague', 'Montgomery',
    'Monty', 'Morey', 'Morgan', 'Morris', 'Morry', 'Mort', 'Mortimer', 'Morton', 'Morty', 'Mose',
    'Moses', 'Moshe', 'Mosi', 'Moss', 'Mouhamadou', 'Mouhamed', 'Mouhammad', 'Moussa',
    'Moustapha', 'Moïse', 'Muhammad', 'Muhammed', 'Munroe', 'Murilo', 'Murphy', 'Murray',
    'Murry', 'Mustafa', 'Mylan', 'Mylann', 'Myles', 'Mylo', 'Máximo', 'Médine', 'Nabil', 'Nacho',
    'Nadir', 'Nael', 'Nahel', 'Nahil', 'Nahim', 'Nahyl', 'Nail', 'Naim', 'Nans', 'Nao',
    'Napoleón', 'Nash', 'Nasir', 'Nassim', 'Nat', 'Natan', 'Nate', 'Nate', 'Nathan', 'Nathanael',
    'Nathanaël', 'Nathaniel', 'Nathaël', 'Nathéo', 'Natty', 'Natéo', 'Navid', 'Nawfel', 'Nayel',
    'Nazim', 'Naël', 'Naín', 'Naïl', 'Naïm', 'Neal', 'Ned', 'Ned', 'Neftalí', 'Nehemiah', 'Neil',
    'Neizan', 'Nel', 'Nell', 'Nels', 'Nelson', 'Nemesio', 'Neo', 'Nessim', 'Nev', 'Nevil',
    'Nevile', 'Nevill', 'Neville', 'Newt', 'Newton', 'Neymar', 'Niall', 'Nicanor', 'Niceto',
    'Nicholas', 'Nick', 'Nicky', 'Nico', 'Nicol', 'Nicolas', 'Nicolas', 'Nicolás', 'Nicomedes',
    'Niels', 'Nige', 'Nigel', 'Niklaus', 'Niko', 'Nikolai', 'Nikolas', 'Nil', 'Nils', 'Nino',
    'Nixon', 'Nizar', 'Noa', 'Noah', 'Noam', 'Noan', 'Noe', 'Noel', 'Noha', 'Noham', 'Nohan',
    'Nohlan', 'Nohé', 'Nolan', 'Nolann', 'Nolhan', 'Noll', 'Nollie', 'Nolly', 'Nor', 'Norbert',
    'Norm', 'Norman', 'Normand', 'Normie', 'Norrie', 'Norris', 'Nort', 'Norton', 'Nour', 'Nowell',
    'Noé', 'Noë', 'Nuada', 'Nuno', 'Néo', 'Oakley', 'Obélix', 'Ocean', 'Octave', 'Odin', 'Odín',
    'Odón', 'Ogmios', 'Oier', 'Oihan', 'Olegario', 'Oliphant', 'Oliver', 'Olivier', 'Olivier',
    'Ollie', 'Olmo', 'Omar', 'Omar', 'Omari', 'Omer', 'Onyx', 'Orencio', 'Orfeo', 'Oriel',
    'Orion', 'Orlando', 'Orson', 'Orv', 'Orville', 'Osbert', 'Osborn', 'Osborne', 'Oscar',
    'Osiel', 'Osiris', 'Osman', 'Osmond', 'Osmund', 'Ossian', 'Ossy', 'Osvaldo', 'Oswald',
    'Oswold', 'Othman', 'Othmane', 'Otis', 'Oto', 'Otoniel', 'Otto', 'Otávio', 'Oumar',
    'Ousmane', 'Oussama', 'Ouways', 'Owen', 'Oz', 'Oz', 'Ozan', 'Oziel', 'Ozzie', 'Ozzy', 'Ozías',
    'Pablo', 'Paco', 'Pacôme', 'Paddy', 'Pantaleón', 'Paolo', 'Paris', 'Parker', 'París', 'Pat',
    'Pat', 'Patricio', 'Patrick', 'Patsy', 'Pau', 'Paul', 'Paulin', 'Paulo', 'Pauly', 'Pavel',
    'Pax', 'Paxton', 'Pedro', 'Pedro Henrique', 'Perce', 'Perceval', 'Percival', 'Percy',
    'Perfecto', 'Perry', 'Pete', 'Peter', 'Petey', 'Petie', 'Petronilo', 'Peyton', 'Pharell',
    'Phil', 'Phil', 'Philip', 'Philippe', 'Phillip', 'Phoenix', 'Pierce', 'Piero', 'Pierre',
    'Pierre', 'Pietro', 'Pip', 'Pol', 'Poldie', 'Policarpo', 'Polonio', 'Poncho', 'Porter',
    'Prakash', 'Preston', 'Priam', 'Primitivo', 'Prince', 'Princeton', 'Prudencio', 'Pío',
    'Qassim', 'Qiang', 'Quentin', 'Quenton', 'Quillan', 'Quincey', 'Quincy', 'Quinn', 'Quintin',
    'Quinton', 'Rael', 'Rafael', 'Rafaël', 'Rafe', 'Raff', 'Rafferty', 'Rahim', 'Raico', 'Raiden',
    'Ralph', 'Ralphy', 'Raman', 'Ramon', 'Ramos', 'Ramón', 'Rand', 'Randal', 'Randall',
    'Randolph', 'Randy', 'Raphael', 'Raphaël', 'Rashid', 'Raul', 'Ravi', 'Ravi Lucca', 'Ray',
    'Rayan', 'Rayane', 'Rayden', 'Rayen', 'Raylan', 'Raymond', 'Raymund', 'Raziel', 'Raúl',
    'Reda', 'Reece', 'Reed', 'Reese', 'Reg', 'Reggie', 'Reginald', 'Regino', 'Reid', 'Reign',
    'Remi', 'Remigio', 'Remington', 'Remy', 'Ren', 'Renato', 'Rene', 'ReneS', 'Renny', 'Reuben',
    'Rex', 'Rex', 'Rey', 'Reynold', 'Rhett', 'Rhodes', 'Rhys', 'Riad', 'Ricardo', 'Rich',
    'Richard', 'Richie', 'Rick', 'Ricky', 'Ricky', 'Ridge', 'Riggs', 'Rigo', 'Rigoberto', 'Riku',
    'Riley', 'Rio', 'River', 'Riyad', 'Rob', 'Rob', 'Robbie', 'Robby', 'Robert', 'Roberto',
    'Robin', 'Rocco', 'Rocky', 'Rod', 'Roddy', 'Roderic', 'Roderick', 'Rodge', 'Rodger', 'Rodney',
    'Rodrigo', 'Roge', 'Roger', 'Rohan', 'Roi', 'Roland', 'Rolf', 'Rolfe', 'Rolly', 'Rolph',
    'Roly', 'Rom', 'Romain', 'Roman', 'Rome', 'Romeo', 'Romy', 'Román', 'Roméo', 'Ron', 'Ronald',
    'Ronaldo', 'Ronan', 'Ronin', 'Ronnie', 'Ronny', 'Ronny', 'Roque', 'Rory', 'Roscoe', 'Ross',
    'Rowan', 'Rowen', 'Rowland', 'Rowly', 'Roy', 'Royce', 'Rube', 'Ruben', 'Rubin', 'Ruby',
    'Rubén', 'Rudo', 'Rudolf', 'Rudolph', 'Rudy', 'Rufe', 'Rufino', 'Rufus', 'Rune', 'Rupert',
    'Ruperto', 'Russ', 'Russel', 'Russell', 'Ry', 'Ryad', 'Ryan', 'Ryatt', 'Ryder', 'Ryker',
    'Rylan', 'Ryland', 'Rémi', 'Rémi', 'Rémy', 'Río', 'Rómulo', 'Saad', 'Sabri', 'Sacha',
    'Saeed', 'Safwan', 'Safwane', 'Sage', 'Said', 'Saint', 'Sajid', 'Sal', 'Sal', 'Salah',
    'Salem', 'Salim', 'Salim', 'Salman', 'Salmane', 'Salomón', 'Salvador', 'Salvatore', 'Sam',
    'Samba', 'Sami', 'Samir', 'Sammy', 'Sampson', 'Samson', 'Samuel', 'Samy', 'Sandalio',
    'Sander', 'Sandro', 'Sanford', 'Santana', 'Santiago', 'Santino', 'Santos', 'Sasha',
    'Saturnino', 'Saul', 'Sawyer', 'Sayan', 'Sayer', 'Saïd', 'Saúl', 'Scott', 'Scotty', 'Sean',
    'Seb', 'Sebastian', 'Sebastián', 'Sedrik', 'Segundo', 'Sekou', 'Selim', 'Selyan', 'Semih',
    'Serapio', 'Serbal', 'Serge', 'Sergio', 'Servando', 'Seth', 'Sevan', 'Severino', 'Sevilin',
    'Sevyn', 'Seydou', 'Seymour', 'Shane', 'Shannon', 'Shanon', 'Shaun', 'Shawn', 'Shel',
    'Sheldon', 'Shelley', 'Shellie', 'Shelly', 'Shelton', 'Shepard', 'Shepherd', 'Sherman',
    'Shiloh', 'Shmuel', 'Si', 'Sid', 'Sidney', 'Silas', 'Silvester', 'Silvestre', 'Simeon',
    'Simie', 'Simmy', 'Simon', 'Siméon', 'Simón', 'Sincere', 'Sinforoso', 'Sinhué', 'Soan',
    'Soann', 'Soen', 'Sofiane', 'Sofronio', 'Sohan', 'Sohann', 'Sol', 'Solal', 'Solan', 'Solly',
    'Solomon', 'Sonny', 'Soren', 'Souhayl', 'Souheyl', 'Soulayman', 'Soulaymane', 'Souleyman',
    'Souleymane', 'Souleymen', 'Soën', 'Spencer', 'Stan', 'Stan', 'Stanislas', 'Stanley', 'Stef',
    'Stefan', 'Steff', 'Steffan', 'Steph', 'Stephan', 'Stephen', 'Sterling', 'Stetson', 'Steve',
    'Steven', 'Stevie', 'Stew', 'Stewart', 'Stimpy', 'Stone', 'Stu', 'Stuart', 'Stéphane',
    'Sucellos', 'Suleyman', 'Sullivan', 'Sutton', 'Swan', 'Swann', 'Sy', 'Syd', 'Sydney', 'Syl',
    'Sylas', 'Sylvain', 'Sylvester', 'Sébastien', 'Sébastien', 'Séneca', 'Sócrates', 'Sören',
    'Taavi', 'Tad', 'Tad', 'Tadeo', 'Taha', 'Tahys', 'Talon', 'Tamim', 'Tanner', 'Tao', 'Taranis',
    'Tariq', 'Tate', 'Tatum', 'Taylor', 'Tayron', 'Ted', 'Ted', 'Teddy', 'Telesforo', 'Teo',
    'Terence', 'Terrance', 'Terrence', 'Terry', 'Teófilo', 'Thad', 'Thaddeus', 'Thadeus',
    'Thales', 'Thao', 'Thatcher', 'Thaïs', 'Theo', 'Theodor', 'Theodore', 'Theodoro', 'Thiago',
    'Thibaud', 'Thibault', 'Thibaut', 'Thilo', 'Thiméo', 'Thomas', 'Thor', 'Thyméo', 'Thélio',
    'Théo', 'Théo', 'Théodore', 'Théophile', 'Tiago', 'Tiberio', 'Tiburcio', 'Tidiane', 'Tilio',
    'Tim', 'Tim', 'Timaé', 'Timaël', 'Timeo', 'Timmy', 'Timoteo', 'Timothy', 'Timothé',
    'Timothée', 'Timoté', 'Timéo', 'Tino', 'Titan', 'Titouan', 'Titus', 'Tiziano', 'Tobi',
    'Tobias', 'Tobie', 'Toby', 'Tobías', 'Todd', 'Tom', 'Tomas', 'Tommy', 'Tomás', 'Tonho',
    'Toño', 'Tony', 'Tony', 'Toph', 'Topher', 'Tor', 'Toribio', 'Trace', 'Tracey', 'Tracy',
    'Trav', 'Travis', 'Trent', 'Trenton', 'Trev', 'Trevor', 'Trey', 'Tripp', 'Tris', 'Tristam',
    'Tristan', 'Tristram', 'Tristán', 'Troy', 'Troy', 'Tru', 'Truett', 'Tucker', 'Ty', 'Ty',
    'Tyago', 'Tyler', 'Tylian', 'Tylio', 'Tymeo', 'Tyméo', 'Tyre', 'Tyron', 'Tyrone', 'Tyson',
    'Télio', 'Téo', 'Udo', 'Ugo', 'Uli', 'Ulises', 'Ulpiano', 'Uly', 'Ulysse', 'Ulysses', 'Umi',
    'Unai', 'Unax', 'Urbano', 'Uri', 'Uria', 'Uriah', 'Urias', 'Uriel', 'Urko', 'Uwe', 'Uxío',
    'Uzziel', 'Uzías', 'Vadim', 'Valentim', 'Valentin', 'Valentine', 'Valentiniano', 'Valentino',
    'Valentín', 'Valerian', 'Valeriano', 'Valerius', 'Vance', 'Vaughan', 'Vaughn', 'Venancio',
    'Vergil', 'Vern', 'Verne', 'Vernon', 'Vester', 'Vianney', 'Vic', 'Vicente', 'Vick', 'Victor',
    'Victor', 'Victoriano', 'Victorino', 'Viggo', 'Vihaan', 'Viktor', 'Ville', 'Vin', 'Vince',
    'Vincent', 'Vincenzo', 'Vinnie', 'Vinny', 'Vinícius', 'Virge', 'Virgil', 'Virgile', 'Viriato',
    'Vito', 'Vitor', 'Víctor', 'Víctor Hugo', 'Wade', 'Wael', 'Wahil', 'Waldo', 'Walid', 'Walker',
    'Wallace', 'Wallie', 'Wallis', 'Wally', 'Walt', 'Walt', 'Walter', 'Warren', 'Wassil',
    'Wassim', 'Watson', 'Waylen', 'Waylon', 'Wayne', 'Waël', 'Waïl', 'Wells', 'Wendell', 'Wes',
    'Wesley', 'Wesson', 'Westin', 'Westley', 'Weston', 'Westyn', 'Wilber', 'Wilbert', 'Wilbur',
    'Wilder', 'Wiley', 'Wilfred', 'Wilfrid', 'Will', 'Will', 'Willard', 'William', 'Willie',
    'Willis', 'Willy', 'Wilmer', 'Wilson', 'Win', 'Winfred', 'Winfrid', 'Winnie', 'Winny',
    'Winston', 'Wissam', 'Wissem', 'Wood', 'Woodrow', 'Woody', 'Wyatt', 'Wylder', 'Xabi',
    'Xabier', 'Xacobe', 'Xan', 'Xan', 'Xander', 'Xanti', 'Xavi', 'Xavier', 'Xavier', 'Xián',
    'Xoel', 'Xosé', 'Xoán', 'Xurxo', 'Yacine', 'Yacoub', 'Yadid', 'Yael', 'Yago', 'Yahia',
    'Yahir', 'Yahya', 'Yamine', 'Yan', 'Yani', 'Yanis', 'Yaniss', 'Yann', 'Yann', 'Yannis',
    'Yasin', 'Yasser', 'Yassin', 'Yassine', 'Yassir', 'Yazid', 'Yaël', 'Yehuda', 'Yerik', 'Yigit',
    'Yisroel', 'Ylan', 'Ylann', 'Ylenzo', 'Ylies', 'Yoan', 'Yoann', 'Yohan', 'Yonatan', 'Yone',
    'Yoni', 'Yosef', 'Youcef', 'Youenn', 'Younes', 'Youness', 'Younès', 'Youri', 'Yousef',
    'Youssef', 'Youssef', 'Youssouf', 'Yunus', 'Yuri', 'Yusuf', 'Yvan', 'Yvann', 'Zac',
    'Zacarías', 'Zach', 'Zachariah', 'Zacharias', 'Zacharie', 'Zacharie', 'Zachary', 'Zack',
    'Zacky', 'Zahir', 'Zaid', 'Zaid', 'Zaiden', 'Zain', 'Zaire', 'Zakai', 'Zakaria', 'Zakariya',
    'Zakarya', 'Zamir', 'Zander', 'Zane', 'Zane', 'Zave', 'Zaven', 'Zavier', 'Zayan', 'Zayd',
    'Zayden', 'Zayn', 'Zayne', 'Zaïm', 'Zechariah', 'Zeke', 'Zen', 'Zeus', 'Zev', 'Ziad',
    'Zinedine', 'Zion', 'Ziyad', 'Zoilo', 'Zyad', 'Zyair', 'Zyaire', 'Zyan', 'Zyon', 'Àlex',
    'Ágabo', 'Álex', 'Álvaro', 'Ángel', 'Éden', 'Édgar', 'Édouard', 'Édouard', 'Élias', 'Élie',
    'Élio', 'Éliott', 'Éloi', 'Émile', 'Éthan', 'Étienne', 'Évan', 'Íker', 'Íñigo', 'Óscar',
    'Ömer'}

set_nomes_femininos_default = {
    'Aadhya', 'Aaliyah', 'Abby', 'Abigail', 'Abril', 'Ada', 'Adalee', 'Adaline', 'Adalyn',
    'Adalynn', 'Addilyn', 'Addilynn', 'Addison', 'Adelaide', 'Adele', 'Adelina', 'Adeline',
    'Adelyn', 'Adelynn', 'Adley', 'Adriana', 'Adrianna', 'Ágata', 'Agatha', 'Aila', 'Ailani',
    'Aileen', 'Ainhoa', 'Ainsley', 'Aisha', 'Aitana', 'Alaia', 'Alaina', 'Alaiya', 'Alana',
    'Alani', 'Alanna', 'Alaya', 'Alayah', 'Alayna', 'Alba', 'Aleah', 'Aleena', 'Alejandra',
    'Alena', 'Alessandra', 'Alessia', 'Alexa', 'Alexandra', 'Alexandria', 'Alexia', 'Alexis',
    'Alia', 'Aliana', 'Alianna', 'Alice', 'Alicia', 'Alina', 'Alison', 'Alisson', 'Alivia',
    'Aliya', 'Aliyah', 'Aliza', 'Allie', 'Allison', 'Allyson', 'Alma', 'Alondra', 'Alora',
    'Alyssa', 'Amaia', 'Amalia', 'Amanda', 'Amani', 'Amara', 'Amari', 'Amaris', 'Amaya', 'Amayah',
    'Amber', 'Amelia', 'Amelie', 'Amina', 'Amira', 'Amirah', 'Amiri', 'Amiyah', 'Amora', 'Amoura',
    'Amy', 'Amélie', 'Amélia', 'Ana', 'Anahi', 'Anais', 'Analia', 'Anastasia', 'Anaya', 'Anaïs',
    'Andi', 'Andrea', 'Angel', 'Angela', 'Angelica', 'Angelina', 'Angelique', 'Angelita', 'Angie',
    'Anika', 'Aniyah', 'Anna', 'Annabelle', 'Annalise', 'Anne', 'Annie', 'Annika', 'Antonella',
    'Anya', 'Arabella', 'Araceli', 'Aracely', 'Araya', 'Ari', 'Aria', 'Ariah', 'Ariana',
    'Arianna', 'Ariel', 'Ariella', 'Arielle', 'Ariya', 'Ariyah', 'Arlet', 'Arleth', 'Arlette',
    'Armani', 'Artemis', 'Arya', 'Ashley', 'Ashlyn', 'Ashlynn', 'Aspen', 'Aspyn', 'Astrid',
    'Athena', 'Aubree', 'Aubrey', 'Aubrie', 'Aubriella', 'Aubrielle', 'Audrey', 'Aurelia',
    'Aurora', 'Aurélie', 'Autumn', 'Ava', 'Avah', 'Avalynn', 'Avayah', 'Averi', 'Averie',
    'Avery', 'Aviana', 'Avianna', 'Aya', 'Ayla', 'Ayleen', 'Aylin', 'Azalea', 'Azaria', 'Azariah',
    'Bailee', 'Bailey', 'Barbara', 'Baylee', 'Baylor', 'Bea', 'Beatrice', 'Belen', 'Bella',
    'Bellamy', 'Belle', 'Berenice', 'Berkley', 'Beth', 'Bethany', 'Bexley', 'Bianca', 'Billie',
    'Birdie', 'Blair', 'Blaire', 'Blake', 'Blakely', 'Blanca', 'Bonnie', 'Braelyn', 'Braelynn',
    'Bria', 'Briana', 'Brianna', 'Briar', 'Bridget', 'Briella', 'Brielle', 'Brinley', 'Bristol',
    'Brittany', 'Brooke', 'Brooklyn', 'Brooklynn', 'Brylee', 'Brynlee', 'Brynleigh', 'Brynn',
    'Cadence', 'Cali', 'Callie', 'Calliope', 'Cameron', 'Camila', 'Camilla', 'Camille', 'Camryn',
    'Candela', 'Capri', 'Cara', 'Carla', 'Carlota', 'Carly', 'Carmen', 'Carolina', 'Caroline',
    'Carter', 'Casey', 'Cassandra', 'Cassidy', 'Cata', 'Cataleya', 'Catalina', 'Catherine',
    'Cecelia', 'Cecilia', 'Celeste', 'Celia', 'Celine', 'Chana', 'Chandler', 'Chanel', 'Charlee',
    'Charleigh', 'Charley', 'Charli', 'Charlie', 'Charlotte', 'Chaya', 'Chayo', 'Chelsea',
    'Cheyenne', 'Chloe', 'Chloé', 'Christina', 'Cielo', 'Claire', 'Clara', 'Claudia',
    'Clementine', 'Cleo', 'Clover', 'Clémence', 'Colette', 'Collins', 'Cora', 'Coraline',
    'Cynthia', 'Dahlia', 'Daisy', 'Dakota', 'Daleyza', 'Dalia', 'Dallas', 'Dana', 'Dani',
    'Daniela', 'Daniella', 'Danielle', 'Danna', 'Daphne', 'Davina', 'Dayana', 'Deborah',
    'Delaney', 'Delfina', 'Delilah', 'Della', 'Demi', 'Denver', 'Destiny', 'Diana', 'Dior',
    'Dolores', 'Dorothy', 'Dream', 'Drew', 'Dulce', 'Dylan', 'Eden', 'Edith', 'Egypt', 'Eileen',
    'Elaina', 'Elaine', 'Eleanor', 'Elena', 'Elia', 'Eliana', 'Elianna', 'Elina', 'Elisa',
    'Elisabeth', 'Elise', 'Eliza', 'Elizabeth', 'Ella', 'Elle', 'Elliana', 'Ellianna', 'Ellie',
    'Elliot', 'Elliott', 'Ellis', 'Elodie', 'Eloise', 'Elora', 'Elowyn', 'Elsa', 'Elsie',
    'Elyse', 'Ember', 'Emberly', 'Emberlynn', 'Emelia', 'Emely', 'Emerald', 'Emerie', 'Emerson',
    'Emersyn', 'Emery', 'Emilia', 'Emiliana', 'Emily', 'Emma', 'Emmalyn', 'Emmeline', 'Emmie',
    'Emmy', 'Emory', 'Ensley', 'Erin', 'Esme', 'Esmeralda', 'Esperanza', 'Estefanía', 'Estefânia',
    'Estella', 'Estelle', 'Esther', 'Estrella', 'Eva', 'Evangeline', 'Eve', 'Evelyn', 'Evelynn',
    'Everlee', 'Everleigh', 'Everly', 'Evie', 'Ezra', 'Faith', 'Fallon', 'Fatima', 'Fay', 'Faye',
    'Felicity', 'Fernanda', 'Finley', 'Fiona', 'Flora', 'Florence', 'Frances', 'Francesca',
    'Frankie', 'Freya', 'Freyja', 'Gabriela', 'Gabriella', 'Gabrielle', 'Gala', 'Galilea',
    'Gemma', 'Genesis', 'Genevieve', 'Georgia', 'Georgina', 'Gia', 'Giana', 'Gianna', 'Giovanna',
    'Girlesa', 'Giselle', 'Giuliana', 'Gloria', 'Goldie', 'Grace', 'Gracelyn', 'Gracelynn',
    'Gracie', 'Greta', 'Guadalupe', 'Guinevere', 'Gwen', 'Gwendolyn', 'Hadassah', 'Hadlee',
    'Hadleigh', 'Hadley', 'Hailey', 'Haisley', 'Haley', 'Halle', 'Hallie', 'Halo', 'Hana',
    'Hanna', 'Hannah', 'Harlee', 'Harley', 'Harlow', 'Harmoni', 'Harmony', 'Harper', 'Hattie',
    'Haven', 'Hayden', 'Hayley', 'Hazel', 'Heaven', 'Heidi', 'Helen', 'Helena', 'Henley',
    'Holland', 'Holly', 'Hope', 'Hunter', 'Ila', 'Iliana', 'Imani', 'Inaya', 'India', 'Indie',
    'Indigo', 'Ines', 'Inès', 'Irene', 'Iris', 'Isabel', 'Isabela', 'Isabella', 'Isabelle',
    'Isla', 'Itzayana', 'Itzel', 'Ivanna', 'Ivory', 'Ivy', 'Iyla', 'Izabella', 'Jacqueline',
    'Jada', 'Jade', 'Jaliyah', 'Jamie', 'Jane', 'Janelle', 'Janiyah', 'Jasmine', 'Jayda',
    'Jayla', 'Jaylah', 'Jaylani', 'Jayleen', 'Jazlyn', 'Jazmin', 'Jazmine', 'Jemma', 'Jen',
    'Jenesis', 'Jenna', 'Jennifer', 'Jessica', 'Jessie', 'Jianna', 'Jimena', 'Jo', 'Joanna',
    'Jocelyn', 'Joelle', 'Johanna', 'Jolene', 'Jolie', 'Jordan', 'Jordyn', 'Josefina',
    'Josephine', 'Josie', 'Journee', 'Journey', 'Journi', 'Jovie', 'Joy', 'Joyce', 'Jream',
    'Juanita', 'Judith', 'Julia', 'Juliana', 'Julianna', 'Julie', 'Juliet', 'Julieta',
    'Juliette', 'Julissa', 'Juniper', 'Justice', 'Kahlani', 'Kai', 'Kaia', 'Kailani', 'Kairi',
    'Kaitlyn', 'Kaiya', 'Kalani', 'Kali', 'Kaliyah', 'Kallie', 'Kamari', 'Kamila', 'Kamilah',
    'Kamiyah', 'Kamryn', 'Kara', 'Karina', 'Karla', 'Karsyn', 'Karter', 'Kassandra', 'Kassidy',
    'Kataleya', 'Katalina', 'Kate', 'Katelyn', 'Katherine', 'Kathryn', 'Katie', 'Kaydence',
    'Kayla', 'Kaylani', 'Kaylee', 'Kayleigh', 'Kehlani', 'Keilani', 'Keily', 'Keira', 'Kelly',
    'Kelsey', 'Kendall', 'Kendra', 'Kenia', 'Kenna', 'Kennedi', 'Kennedy', 'Kensley', 'Kenzie',
    'Keyla', 'Khalani', 'Khaleesi', 'Khloe', 'Kiana', 'Kiara', 'Kimber', 'Kimberly', 'Kinley',
    'Kinslee', 'Kinsley', 'Kira', 'Kora', 'Kori', 'Kyla', 'Kylee', 'Kylie', 'Kyra', 'Lacey',
    'Laia', 'Laila', 'Lainey', 'Lakelyn', 'Lakelynn', 'Lana', 'Laney', 'Lara', 'Laura', 'Laurel',
    'Lauren', 'Lauryn', 'Layla', 'Laylah', 'Laylani', 'Layne', 'Lea', 'Leah', 'Leanna', 'Legacy',
    'Leia', 'Leighton', 'Leila', 'Leilani', 'Leilany', 'Lena', 'Lennon', 'Lennox', 'Lenora',
    'Leona', 'Leslie', 'Lesly', 'Lexi', 'Lexie', 'Leyla', 'Lia', 'Liana', 'Liberty', 'Lila',
    'Lilah', 'Lilian', 'Liliana', 'Lilianna', 'Lilith', 'Lillian', 'Lilliana', 'Lillie', 'Lilly',
    'Lily', 'Lilyana', 'Lina', 'Linda', 'Lisa', 'Liv', 'Livia', 'Lizbeth', 'Lizette', 'Logan',
    'Lola', 'London', 'Londyn', 'Lorelai', 'Lorelei', 'Loretta', 'Lottie', 'Louisa', 'Louise',
    'Lucia', 'Luciana', 'Lucille', 'Lucy', 'Lucía', 'Luella', 'Luisa', 'Lula', 'Luna', 'Lupe',
    'Luz', 'Lydia', 'Lyla', 'Lylah', 'Lyra', 'Lyric', 'Léa', 'Mabel', 'Maci', 'Macie',
    'Mackenzie', 'Macy', 'Madalyn', 'Maddie', 'Maddison', 'Madeleine', 'Madeline', 'Madelyn',
    'Madelynn', 'Madilyn', 'Madilynn', 'Madison', 'Madisyn', 'Mae', 'Maeve', 'Magda',
    'Magdalena', 'Maggie', 'Magnolia', 'Maha', 'Maia', 'Maisie', 'Maisy', 'Makayla', 'Makenna',
    'Makenzie', 'Malani', 'Malaya', 'Malayah', 'Malaysia', 'Maleah', 'Malia', 'Maliyah',
    'Mallory', 'Manon', 'Mara', 'Marceline', 'Maren', 'Margaret', 'Margo', 'Margot', 'Maria',
    'Mariah', 'Mariam', 'Marian', 'Mariana', 'Marianna', 'Maricela', 'Marie', 'Mariela',
    'Marigold', 'Marilyn', 'Marina', 'Marisol', 'Maritza', 'Marlee', 'Marleigh', 'Marley',
    'Marlowe', 'Marta', 'Martha', 'Martina', 'Mary', 'Maryam', 'Mathilde', 'Matilda', 'Mavis',
    'Maxine', 'Maya', 'Mckenna', 'Mckenzie', 'Mckinley', 'Meadow', 'Meche', 'Megan', 'Meilani',
    'Melanie', 'Melany', 'Melina', 'Melissa', 'Melody', 'Mercy', 'Meredith', 'Mia', 'Michaela',
    'Michelle', 'Mikaela', 'Mikayla', 'Mila', 'Milan', 'Milana', 'Milani', 'Milena', 'Miley',
    'Millie', 'Mina', 'Mira', 'Miracle', 'Miranda', 'Miriam', 'Molly', 'Monica', 'Monroe',
    'Morgan', 'Mya', 'Myla', 'Mylah', 'Myra', 'Nadia', 'Nala', 'Nalani', 'Nancy', 'Naomi',
    'Natalia', 'Natalie', 'Natasha', 'Nathalia', 'Navy', 'Naya', 'Nayeli', 'Nellie', 'Neriah',
    'Nevaeh', 'Nia', 'Nicole', 'Nina', 'Noa', 'Noah', 'Noelle', 'Noemi', 'Nola', 'Noor', 'Nora',
    'Norah', 'Nori', 'Nour', 'Novah', 'Novalee', 'Nyla', 'Nylah', 'Nyomi', 'Nyra', 'Oaklee',
    'Oakleigh', 'Oakley', 'Oaklyn', 'Oaklynn', 'Ocean', 'Octavia', 'Olive', 'Olivia', 'Opal',
    'Ophelia', 'Paige', 'Paislee', 'Paisley', 'Palmer', 'Paloma', 'Pam', 'Paola', 'Paris',
    'Parker', 'Paula', 'Paulina', 'Pauline', 'Payton', 'Pearl', 'Penelope', 'Penny', 'Perla',
    'Persephone', 'Peyton', 'Phoebe', 'Phoenix', 'Piper', 'Poppy', 'Presley', 'Princess',
    'Priscilla', 'Promise', 'Quinn', 'Rachel', 'Rae', 'Raegan', 'Raelyn', 'Raelynn', 'Raina',
    'Ramona', 'Rania', 'Raven', 'Raya', 'Rayna', 'Rayne', 'Reagan', 'Rebecca', 'Rebekah',
    'Reese', 'Regina', 'Reign', 'Reina', 'Remi', 'Remington', 'Remy', 'Renata', 'Reyna', 'Rhea',
    'Ria', 'Riley', 'Rivka', 'Robin', 'Rocio', 'Roma', 'Romina', 'Rory', 'Rosa', 'Rosalee',
    'Rosalia', 'Rosalie', 'Rosalina', 'Rosalyn', 'Rose', 'Roselyn', 'Rosemary', 'Rosie', 'Rowan',
    'Rowyn', 'Ruby', 'Ruth', 'Ryann', 'Rylan', 'Rylee', 'Ryleigh', 'Rylie', 'Saanvi', 'Sabrina',
    'Sadie', 'Sage', 'Saige', 'Salem', 'Salma', 'Samantha', 'Samara', 'Samira', 'Sandy',
    'Saoirse', 'Sapphire', 'Sara', 'Sarah', 'Sarahi', 'Sarai', 'Sariah', 'Sariyah', 'Sasha',
    'Savanna', 'Savannah', 'Sawyer', 'Saylor', 'Scarlet', 'Scarlett', 'Scarlette', 'Scottie',
    'Scout', 'Selah', 'Selena', 'Selene', 'Serena', 'Serenity', 'Sevyn', 'Shay', 'Shelby',
    'Shiloh', 'Siena', 'Sienna', 'Sierra', 'Silvia', 'Simone', 'Sky', 'Skye', 'Skyla', 'Sloan',
    'Sloane', 'Sofia', 'Sofía', 'Sol', 'Soleil', 'Sophia', 'Sophie', 'Stacey', 'Stacey', 'Stacy',
    'Stella', 'Stephanie', 'Stevie', 'Stormi', 'Summer', 'Sunny', 'Susana', 'Sutton', 'Sydney',
    'Sylvia', 'Sylvie', 'Tala', 'Talia', 'Tatum', 'Taylor', 'Taytum', 'Teagan', 'Tere', 'Teresa',
    'Tess', 'Tessa', 'Thalia', 'Thea', 'Theodora', 'Tia', 'Tiana', 'Tiffany', 'Tinsley', 'Toña',
    'Treasure', 'Triana', 'Trinity', 'Tru', 'Una', 'Vada', 'Valentina', 'Valeria', 'Valerie',
    'Valery', 'Valérie', 'Vanessa', 'Veda', 'Vega', 'Vera', 'Veronica', 'Victoria', 'Vida',
    'Vienna', 'Violet', 'Violeta', 'Virginia', 'Vivian', 'Viviana', 'Vivienne', 'Waverly',
    'Whitley', 'Willa', 'Willow', 'Winnie', 'Winona', 'Winter', 'Wren', 'Wrenlee', 'Wrenley',
    'Wynter', 'Xia', 'Ximena', 'Xiomara', 'Xyla', 'Yamileth', 'Yara', 'Yareli', 'Yaretzi',
    'Yasmin', 'Yesenia', 'Zahra', 'Zainab', 'Zaniyah', 'Zara', 'Zaria', 'Zariah', 'Zariyah',
    'Zayla', 'Zaylee', 'Zelda', 'Zendaya', 'Zhuri', 'Zoe', 'Zoey', 'Zora', 'Zoya', 'Zoé', 'Zuri',
    'Élodie'}

traduções_nomes = {('Aaron', 'Arão'),
                   ('Aaron', 'Áaron'),
                   ('Adam', 'Adão'),
                   ('Adrian', 'Adriano'),
                   ('Agatha', 'Ágata'),
                   ('Albert', 'Alberto'),
                   ('Alejandra', 'Alexandra'),
                   ('Alejandro', 'Alexandre'),
                   ('Alexander', 'Alexandre'),
                   ('Alfred', 'Alfredo'),
                   ('Allan', 'Alan'),
                   ('Amelia', 'Amélia'),
                   ('Andrea', 'Andreia'),
                   ('Andrea', 'Andréia'),
                   ('Andrea', 'Andréia'),
                   ('Andrew', 'André'),
                   ('Angela', 'Ângela'),
                   ('Anna', 'Ana'),
                   ('Anthony', 'Antônio'),
                   ('Antónia', 'Antônia'),
                   ('António', 'Antônio'),
                   ('Aracely', 'Araceli'),
                   ('Arthur', 'Artur'),
                   ('Augustín', 'Augusto'),
                   ('Aurelio', 'Aurélio'),
                   ('Barb', 'Barbe'),
                   ('Beatrice', 'Beatriz'),
                   ('Benedict', 'Benedito'),
                   ('Benedicta', 'Benedita'),
                   ('Benjamin', 'Benjamim'),
                   ('Bernard', 'Bernardo'),
                   ('Bethany', 'Betânia'),
                   ('Bridget', 'Brigite'),
                   ('Camilla', 'Camila'),
                   ('Carl', 'Carlo'),
                   ('Carl', 'Carlos'),
                   ('Carmen', 'Carmem'),
                   ('Catalina', 'Catarina'),
                   ('Catherine', 'Catarina'),
                   ('Catherine', 'Catharina'),
                   ('Charles', 'Carlos'),
                   ('Charlie', 'Carlos'),
                   ('Charlotte', 'Carlota'),
                   ('Chloe', 'Chloé'),
                   ('Christina', 'Cristina'),
                   ('Christine', 'Cristine'),
                   ('Christopher', 'Cristóvão'),
                   ('Christopher', 'Cristóvão'),
                   ('Clayton', 'Claiton'),
                   ('Clayton', 'Cleiton'),
                   ('Clovis', 'Clóvis'),
                   ('Constanza', 'Constança'),
                   ('Daniel', 'Daniel'),
                   ('Daniella', 'Daniela'),
                   ('Danielle', 'Daniele'),
                   ('David', 'Davi'),
                   ('Dennis', 'Dênis'),
                   ('Edmond', 'Edmundo'),
                   ('Edmund', 'Edmundo'),
                   ('Edward', 'Eduardo'),
                   ('Eleanor', 'Eleonor'),
                   ('Eleanor', 'Eleonora'),
                   ('Elijah', 'Elias'),
                   ('Elisabeht', 'Isabel'),
                   ('Elisabeth', 'Elizabete'),
                   ('Elizabeth', 'Elizabete'),
                   ('Elizabeth', 'Isabel'),
                   ('Emilia', 'Emília'),
                   ('Emily', 'Emília'),
                   ('Emily', 'Emília'),
                   ('Emma', 'Ema'),
                   ('Enrique', 'Henrique'),
                   ('Eric', 'Érico'),
                   ('Estefanía', 'Estefânia'),
                   ('Ethan', 'Éthan'),
                   ('Fatima', 'Fátima'),
                   ('Frederick', 'Frederico'),
                   ('Gaston', 'Gastão'),
                   ('George', 'Jorge'),
                   ('Gerald', 'Geraldo'),
                   ('Gilbert', 'Gilberto'),
                   ('Gonzalo', 'Gonçalo'),
                   ('Grace', 'Graça'),
                   ('Grace', 'Greice'),
                   ('Gregory', 'Gregório'),
                   ('Guillermo', 'Guilherme'),
                   ('Harold', 'Haroldo'),
                   ('Helen', 'Helena'),
                   ('Henry', 'Henrique'),
                   ('Horace', 'Horácio'),
                   ('Héctor', 'Heitor'),
                   ('Ignacio', 'Inácio'),
                   ('Isabella', 'Isabela'),
                   ('Jacob', 'Jacó'),
                   ('James', 'Thiago'),
                   ('James', 'Tiago'),
                   ('James', 'Tiago'),
                   ('Janet', 'Janete'),
                   ('Jason', 'Jasão'),
                   ('Javier', 'Xavier'),
                   ('Jennifer', 'Jenifer'),
                   ('Jessica', 'Jéssica'),
                   ('Jesús', 'Jesus'),
                   ('Joe', 'Jo'),
                   ('John', 'João'),
                   ('Johnathan', 'Jonatan'),
                   ('Johnathan', 'João'),
                   ('Joseph', 'José'),
                   ('Josephine', 'Josefina'),
                   ('Joshua', 'Josué'),
                   ('Joyce', 'Joice'),
                   ('Juan', 'João'),
                   ('Julian', 'Juliano'),
                   ('Justin', 'Justino'),
                   ('Leonard', 'Leonardo'),
                   ('Lily', 'Lílian'),
                   ('Louise', 'Luisa'),
                   ('Louise', 'Luiza'),
                   ('Louise', 'Luísa'),
                   ('Louise', 'Luíza'),
                   ('Lucía', 'Lúcia'),
                   ('Luis', 'Luís'),
                   ('Luke', 'Lucas'),
                   ('Margaret', 'Margarete'),
                   ('Margaret', 'Margarida'),
                   ('Margareth', 'Margarete'),
                   ('Mariah', 'Maria'),
                   ('Marian', 'Mariana'),
                   ('Mark', 'Marcos'),
                   ('Martha', 'Marta'),
                   ('Martin', 'Martinho'),
                   ('Mary', 'Maria'),
                   ('Mary', 'Maria'),
                   ('María', 'Maria'),
                   ('Mateo', 'Mateus'),
                   ('Mateo', 'Matheus'),
                   ('Mathew', 'Mateus'),
                   ('Mathew', 'Matheus'),
                   ('Matthew', 'Mateus'),
                   ('Matías', 'Matias'),
                   ('Maurice', 'Maurício'),
                   ('Michael', 'Miguel'),
                   ('Michelle', 'Michele'),
                   ('Monica', 'Mônica'),
                   ('Nathan', 'Natan'),
                   ('Noah', 'Noé'),
                   ('Octavio', 'Otávio'),
                   ('Olivia', 'Olívia'),
                   ('Oswald', 'Osvaldo'),
                   ('Pamela', 'Pâmela'),
                   ('Patricia', 'Patrícia'),
                   ('Patrick', 'Patrício'),
                   ('Paul', 'Paulo'),
                   ('Peter', 'Pedro'),
                   ('Philip', 'Felipe'),
                   ('Rachel', 'Raquel'),
                   ('Ramón', 'Ramon'),
                   ('Raphael', 'Rafael'),
                   ('Rebecca', 'Rebeca'),
                   ('Richard', 'Ricardo'),
                   ('Robert', 'Roberto'),
                   ('Rodger', 'Roger'),
                   ('Rodger', 'Rogério'),
                   ('Ronald', 'Ronaldo'),
                   ('Rosario', 'Rosário'),
                   ('Samantha', 'Samanta'),
                   ('Sarah', 'Sara'),
                   ('Sebastián', 'Sebastião'),
                   ('Sylvia', 'Sílvia'),
                   ('Silvia', 'Sílvia'),
                   ('Sofía', 'Sofia'),
                   ('Sophia', 'Sofia'),
                   ('Steve', 'Estevão'),
                   ('Sydney', 'Sidnei'),
                   ('Sydney', 'Sidney'),
                   ('Thomas', 'Tomás'),
                   ('Timothy', 'Timóteo'),
                   ('Victor', 'Vitor'),
                   ('Victoria', 'Victória'),
                   ('Victoria', 'Vitória'),
                   ('Vincent', 'Vicente'),
                   ('Walter', 'Valter'),
                   ('William', 'Guilherme'),
                   ('Zachary', 'Zacarias'),
                   ('Ángel', 'Ângelo')
                   }
